// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct LiquidityPoolClientProgram;
impl sails_rs::client::Program for LiquidityPoolClientProgram {}
pub trait LiquidityPoolClient {
    type Env: sails_rs::client::GearEnv;
    fn pool(&self) -> sails_rs::client::Service<pool::PoolImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> LiquidityPoolClient
    for sails_rs::client::Actor<LiquidityPoolClientProgram, E>
{
    type Env = E;
    fn pool(&self) -> sails_rs::client::Service<pool::PoolImpl, Self::Env> {
        self.service(stringify!(Pool))
    }
}
pub trait LiquidityPoolClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        owner: ActorId,
        token_program: ActorId,
        capacity_multiplier_bps: u16,
    ) -> sails_rs::client::PendingCtor<LiquidityPoolClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> LiquidityPoolClientCtors
    for sails_rs::client::Deployment<LiquidityPoolClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        owner: ActorId,
        token_program: ActorId,
        capacity_multiplier_bps: u16,
    ) -> sails_rs::client::PendingCtor<LiquidityPoolClientProgram, io::Create, Self::Env> {
        self.pending_ctor((owner, token_program, capacity_multiplier_bps))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (owner: ActorId, token_program: ActorId, capacity_multiplier_bps: u16) -> ());
}

pub mod pool {
    use super::*;
    pub trait Pool {
        type Env: sails_rs::client::GearEnv;
        fn authorize_market(
            &mut self,
            market: ActorId,
        ) -> sails_rs::client::PendingCall<io::AuthorizeMarket, Self::Env>;
        fn deposit_liquidity(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::DepositLiquidity, Self::Env>;
        fn pay_out_to_vault(
            &mut self,
            vault: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::PayOutToVault, Self::Env>;
        fn release_notional(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ReleaseNotional, Self::Env>;
        fn reserve_notional(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ReserveNotional, Self::Env>;
        fn revoke_market(
            &mut self,
            market: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMarket, Self::Env>;
        fn withdraw_liquidity(
            &mut self,
            shares: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawLiquidity, Self::Env>;
        fn account(
            &self,
            provider: ActorId,
        ) -> sails_rs::client::PendingCall<io::Account, Self::Env>;
        fn pool_state(&self) -> sails_rs::client::PendingCall<io::PoolState, Self::Env>;
    }
    pub struct PoolImpl;
    impl<E: sails_rs::client::GearEnv> Pool for sails_rs::client::Service<PoolImpl, E> {
        type Env = E;
        fn authorize_market(
            &mut self,
            market: ActorId,
        ) -> sails_rs::client::PendingCall<io::AuthorizeMarket, Self::Env> {
            self.pending_call((market,))
        }
        fn deposit_liquidity(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::DepositLiquidity, Self::Env> {
            self.pending_call((amount,))
        }
        fn pay_out_to_vault(
            &mut self,
            vault: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::PayOutToVault, Self::Env> {
            self.pending_call((vault, amount))
        }
        fn release_notional(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ReleaseNotional, Self::Env> {
            self.pending_call((amount,))
        }
        fn reserve_notional(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ReserveNotional, Self::Env> {
            self.pending_call((amount,))
        }
        fn revoke_market(
            &mut self,
            market: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMarket, Self::Env> {
            self.pending_call((market,))
        }
        fn withdraw_liquidity(
            &mut self,
            shares: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawLiquidity, Self::Env> {
            self.pending_call((shares,))
        }
        fn account(
            &self,
            provider: ActorId,
        ) -> sails_rs::client::PendingCall<io::Account, Self::Env> {
            self.pending_call((provider,))
        }
        fn pool_state(&self) -> sails_rs::client::PendingCall<io::PoolState, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AuthorizeMarket (market: ActorId) -> ());
        sails_rs::io_struct_impl!(DepositLiquidity (amount: u128) -> super::LpAccount);
        sails_rs::io_struct_impl!(PayOutToVault (vault: ActorId, amount: u128) -> super::PoolState);
        sails_rs::io_struct_impl!(ReleaseNotional (amount: u128) -> super::PoolState);
        sails_rs::io_struct_impl!(ReserveNotional (amount: u128) -> super::PoolState);
        sails_rs::io_struct_impl!(RevokeMarket (market: ActorId) -> ());
        sails_rs::io_struct_impl!(WithdrawLiquidity (shares: u128) -> super::LpAccount);
        sails_rs::io_struct_impl!(Account (provider: ActorId) -> super::LpAccount);
        sails_rs::io_struct_impl!(PoolState () -> super::PoolState);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum PoolEvents {
            LiquidityDeposited {
                provider: ActorId,
                amount: u128,
                shares: u128,
            },
            LiquidityWithdrawn {
                provider: ActorId,
                amount: u128,
                shares: u128,
            },
            CapacityReserved {
                market: ActorId,
                amount: u128,
                reserved_notional: u128,
            },
            CapacityReleased {
                market: ActorId,
                amount: u128,
                reserved_notional: u128,
            },
            ProfitPaidToVault {
                market: ActorId,
                vault: ActorId,
                amount: u128,
            },
            MarketAuthorizationChanged {
                market: ActorId,
                enabled: bool,
            },
        }
        impl sails_rs::client::Event for PoolEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "LiquidityDeposited",
                "LiquidityWithdrawn",
                "CapacityReserved",
                "CapacityReleased",
                "ProfitPaidToVault",
                "MarketAuthorizationChanged",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for PoolImpl {
            type Event = PoolEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LpAccount {
    pub shares: u128,
    pub deposited: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PoolState {
    pub total_liquidity: u128,
    pub total_shares: u128,
    pub reserved_notional: u128,
    pub max_capacity: u128,
}
