[package]
name = "liquidity-pool-app"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Business logic for the Varix LP pool"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
demo-usdc-vft-client.workspace = true
sails-rs.workspace = true
