// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct PerpMarketClientProgram;
impl sails_rs::client::Program for PerpMarketClientProgram {}
pub trait PerpMarketClient {
    type Env: sails_rs::client::GearEnv;
    fn market(&self) -> sails_rs::client::Service<market::MarketImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> PerpMarketClient
    for sails_rs::client::Actor<PerpMarketClientProgram, E>
{
    type Env = E;
    fn market(&self) -> sails_rs::client::Service<market::MarketImpl, Self::Env> {
        self.service(stringify!(Market))
    }
}
pub trait PerpMarketClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        config: MarketConfig,
        initial_mark_price: u128,
        initial_index_price: u128,
    ) -> sails_rs::client::PendingCtor<PerpMarketClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> PerpMarketClientCtors
    for sails_rs::client::Deployment<PerpMarketClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        config: MarketConfig,
        initial_mark_price: u128,
        initial_index_price: u128,
    ) -> sails_rs::client::PendingCtor<PerpMarketClientProgram, io::Create, Self::Env> {
        self.pending_ctor((config, initial_mark_price, initial_index_price))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (config: super::MarketConfig, initial_mark_price: u128, initial_index_price: u128) -> ());
}

pub mod market {
    use super::*;
    pub trait Market {
        type Env: sails_rs::client::GearEnv;
        fn add_margin(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::AddMargin, Self::Env>;
        fn check_liquidation(
            &mut self,
            trader: ActorId,
        ) -> sails_rs::client::PendingCall<io::CheckLiquidation, Self::Env>;
        fn close_position(
            &mut self,
            size: u128,
        ) -> sails_rs::client::PendingCall<io::ClosePosition, Self::Env>;
        fn open_position(
            &mut self,
            side: Side,
            size: u128,
            leverage: u8,
            margin: u128,
            _max_slippage_bps: u16,
        ) -> sails_rs::client::PendingCall<io::OpenPosition, Self::Env>;
        fn settle_funding(&mut self)
        -> sails_rs::client::PendingCall<io::SettleFunding, Self::Env>;
        fn update_price(
            &mut self,
            mark_price: u128,
            index_price: u128,
        ) -> sails_rs::client::PendingCall<io::UpdatePrice, Self::Env>;
        fn config(&self) -> sails_rs::client::PendingCall<io::Config, Self::Env>;
        fn market_state(&self) -> sails_rs::client::PendingCall<io::MarketState, Self::Env>;
        fn position(
            &self,
            trader: ActorId,
        ) -> sails_rs::client::PendingCall<io::Position, Self::Env>;
    }
    pub struct MarketImpl;
    impl<E: sails_rs::client::GearEnv> Market for sails_rs::client::Service<MarketImpl, E> {
        type Env = E;
        fn add_margin(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::AddMargin, Self::Env> {
            self.pending_call((amount,))
        }
        fn check_liquidation(
            &mut self,
            trader: ActorId,
        ) -> sails_rs::client::PendingCall<io::CheckLiquidation, Self::Env> {
            self.pending_call((trader,))
        }
        fn close_position(
            &mut self,
            size: u128,
        ) -> sails_rs::client::PendingCall<io::ClosePosition, Self::Env> {
            self.pending_call((size,))
        }
        fn open_position(
            &mut self,
            side: Side,
            size: u128,
            leverage: u8,
            margin: u128,
            _max_slippage_bps: u16,
        ) -> sails_rs::client::PendingCall<io::OpenPosition, Self::Env> {
            self.pending_call((side, size, leverage, margin, _max_slippage_bps))
        }
        fn settle_funding(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::SettleFunding, Self::Env> {
            self.pending_call(())
        }
        fn update_price(
            &mut self,
            mark_price: u128,
            index_price: u128,
        ) -> sails_rs::client::PendingCall<io::UpdatePrice, Self::Env> {
            self.pending_call((mark_price, index_price))
        }
        fn config(&self) -> sails_rs::client::PendingCall<io::Config, Self::Env> {
            self.pending_call(())
        }
        fn market_state(&self) -> sails_rs::client::PendingCall<io::MarketState, Self::Env> {
            self.pending_call(())
        }
        fn position(
            &self,
            trader: ActorId,
        ) -> sails_rs::client::PendingCall<io::Position, Self::Env> {
            self.pending_call((trader,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddMargin (amount: u128) -> super::Position);
        sails_rs::io_struct_impl!(CheckLiquidation (trader: ActorId) -> bool);
        sails_rs::io_struct_impl!(ClosePosition (size: u128) -> super::ClosedPosition);
        sails_rs::io_struct_impl!(OpenPosition (side: super::Side, size: u128, leverage: u8, margin: u128, _max_slippage_bps: u16) -> super::Position);
        sails_rs::io_struct_impl!(SettleFunding () -> super::MarketSnapshot);
        sails_rs::io_struct_impl!(UpdatePrice (mark_price: u128, index_price: u128) -> super::MarketSnapshot);
        sails_rs::io_struct_impl!(Config () -> super::MarketConfig);
        sails_rs::io_struct_impl!(MarketState () -> super::MarketSnapshot);
        sails_rs::io_struct_impl!(Position (trader: ActorId) -> Option<super::Position>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum MarketEvents {
            PriceUpdated {
                mark_price: u128,
                index_price: u128,
            },
            PositionOpened {
                trader: ActorId,
                position: Position,
            },
            PositionClosed {
                trader: ActorId,
                close: ClosedPosition,
            },
            MarginAdded {
                trader: ActorId,
                new_margin: u128,
            },
            FundingSettled {
                funding_rate_bps: i128,
                cumulative_funding_rate_bps: i128,
                block: u32,
            },
            Liquidated {
                trader: ActorId,
                mark_price: u128,
                equity: i128,
                maintenance_margin: u128,
            },
        }
        impl sails_rs::client::Event for MarketEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "PriceUpdated",
                "PositionOpened",
                "PositionClosed",
                "MarginAdded",
                "FundingSettled",
                "Liquidated",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for MarketImpl {
            type Event = MarketEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MarketConfig {
    pub owner: ActorId,
    pub asset: Asset,
    pub oracle_service: Option<ActorId>,
    pub margin_vault: Option<ActorId>,
    pub session_registry: Option<ActorId>,
    pub risk: MarketRiskConfig,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Asset {
    Btc,
    Eth,
    Sol,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MarketRiskConfig {
    pub initial_margin_bps: u16,
    pub maintenance_margin_bps: u16,
    pub max_leverage: u8,
    pub funding_interval_blocks: u32,
    pub liquidation_delay_blocks: u32,
    pub max_funding_velocity_bps: i16,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Position {
    pub size: i128,
    pub entry_price: u128,
    pub margin: u128,
    pub leverage: u8,
    pub last_funding_rate_bps: i128,
    pub opened_at: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ClosedPosition {
    pub realized_pnl: i128,
    pub funding_paid: i128,
    pub remaining_margin: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Side {
    Long,
    Short,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MarketSnapshot {
    pub mark_price: u128,
    pub index_price: u128,
    pub funding_rate_bps: i128,
    pub cumulative_funding_rate_bps: i128,
    pub open_interest_long: u128,
    pub open_interest_short: u128,
}
