// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct PerpMarketClientProgram;
impl sails_rs::client::Program for PerpMarketClientProgram {}
pub trait PerpMarketClient {
    type Env: sails_rs::client::GearEnv;
    fn market(&self) -> sails_rs::client::Service<market::MarketImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> PerpMarketClient
    for sails_rs::client::Actor<PerpMarketClientProgram, E>
{
    type Env = E;
    fn market(&self) -> sails_rs::client::Service<market::MarketImpl, Self::Env> {
        self.service(stringify!(Market))
    }
}
pub trait PerpMarketClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        config: MarketConfig,
        initial_mark_price: u128,
        initial_index_price: u128,
    ) -> sails_rs::client::PendingCtor<PerpMarketClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> PerpMarketClientCtors
    for sails_rs::client::Deployment<PerpMarketClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        config: MarketConfig,
        initial_mark_price: u128,
        initial_index_price: u128,
    ) -> sails_rs::client::PendingCtor<PerpMarketClientProgram, io::Create, Self::Env> {
        self.pending_ctor((config, initial_mark_price, initial_index_price))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (config: super::MarketConfig, initial_mark_price: u128, initial_index_price: u128) -> ());
}

pub mod market {
    use super::*;
    pub trait Market {
        type Env: sails_rs::client::GearEnv;
        fn add_margin(
            &mut self,
            position_id: u64,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::AddMargin, Self::Env>;
        fn check_liquidation(
            &mut self,
            trader: ActorId,
        ) -> sails_rs::client::PendingCall<io::CheckLiquidation, Self::Env>;
        fn close_position(
            &mut self,
            position_id: u64,
            size: u128,
        ) -> sails_rs::client::PendingCall<io::ClosePosition, Self::Env>;
        fn open_position(
            &mut self,
            side: Side,
            size: u128,
            leverage: u16,
            margin: u128,
            max_slippage_bps: u16,
        ) -> sails_rs::client::PendingCall<io::OpenPosition, Self::Env>;
        /// Owner-only: set the taker fee (basis points of traded notional) charged on
        /// position opens. `0` disables fees.
        fn set_fees(
            &mut self,
            taker_fee_bps: u16,
        ) -> sails_rs::client::PendingCall<io::SetFees, Self::Env>;
        /// Owner-only: set the funding skew coefficient (basis points applied at a
        /// fully one-sided book). `0` falls back to pure premium funding.
        fn set_funding_skew(
            &mut self,
            coefficient_bps: u16,
        ) -> sails_rs::client::PendingCall<io::SetFundingSkew, Self::Env>;
        /// Owner-only: configure liquidations. `penalty_bps` is charged on the
        /// liquidated notional and routed to the insurance fund; `fraction_bps` is
        /// the share of a position closed per liquidation call (`0` or `>= 10_000`
        /// closes the whole position).
        fn set_liquidation_config(
            &mut self,
            penalty_bps: u16,
            fraction_bps: u16,
        ) -> sails_rs::client::PendingCall<io::SetLiquidationConfig, Self::Env>;
        /// Owner-only: cap the open interest allowed on each side of the book. `0`
        /// means uncapped.
        fn set_oi_cap(
            &mut self,
            max_oi_per_side: u128,
        ) -> sails_rs::client::PendingCall<io::SetOiCap, Self::Env>;
        /// Owner-only: bound how far a single `update_price` may move the mark/index
        /// from the previous value, in basis points. `0` disables the circuit breaker.
        fn set_price_guard(
            &mut self,
            max_price_deviation_bps: u16,
        ) -> sails_rs::client::PendingCall<io::SetPriceGuard, Self::Env>;
        fn settle_funding(&mut self)
        -> sails_rs::client::PendingCall<io::SettleFunding, Self::Env>;
        fn update_price(
            &mut self,
            mark_price: u128,
            index_price: u128,
        ) -> sails_rs::client::PendingCall<io::UpdatePrice, Self::Env>;
        fn config(&self) -> sails_rs::client::PendingCall<io::Config, Self::Env>;
        fn fee_config(&self) -> sails_rs::client::PendingCall<io::FeeConfig, Self::Env>;
        fn funding_skew(&self) -> sails_rs::client::PendingCall<io::FundingSkew, Self::Env>;
        fn liquidation_fraction_bps(
            &self,
        ) -> sails_rs::client::PendingCall<io::LiquidationFractionBps, Self::Env>;
        fn liquidation_penalty_bps(
            &self,
        ) -> sails_rs::client::PendingCall<io::LiquidationPenaltyBps, Self::Env>;
        fn market_state(&self) -> sails_rs::client::PendingCall<io::MarketState, Self::Env>;
        fn oi_cap(&self) -> sails_rs::client::PendingCall<io::OiCap, Self::Env>;
        fn position(
            &self,
            position_id: u64,
        ) -> sails_rs::client::PendingCall<io::Position, Self::Env>;
        fn positions(
            &self,
            trader: ActorId,
        ) -> sails_rs::client::PendingCall<io::Positions, Self::Env>;
        fn price_guard(&self) -> sails_rs::client::PendingCall<io::PriceGuard, Self::Env>;
    }
    pub struct MarketImpl;
    impl<E: sails_rs::client::GearEnv> Market for sails_rs::client::Service<MarketImpl, E> {
        type Env = E;
        fn add_margin(
            &mut self,
            position_id: u64,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::AddMargin, Self::Env> {
            self.pending_call((position_id, amount))
        }
        fn check_liquidation(
            &mut self,
            trader: ActorId,
        ) -> sails_rs::client::PendingCall<io::CheckLiquidation, Self::Env> {
            self.pending_call((trader,))
        }
        fn close_position(
            &mut self,
            position_id: u64,
            size: u128,
        ) -> sails_rs::client::PendingCall<io::ClosePosition, Self::Env> {
            self.pending_call((position_id, size))
        }
        fn open_position(
            &mut self,
            side: Side,
            size: u128,
            leverage: u16,
            margin: u128,
            max_slippage_bps: u16,
        ) -> sails_rs::client::PendingCall<io::OpenPosition, Self::Env> {
            self.pending_call((side, size, leverage, margin, max_slippage_bps))
        }
        fn set_fees(
            &mut self,
            taker_fee_bps: u16,
        ) -> sails_rs::client::PendingCall<io::SetFees, Self::Env> {
            self.pending_call((taker_fee_bps,))
        }
        fn set_funding_skew(
            &mut self,
            coefficient_bps: u16,
        ) -> sails_rs::client::PendingCall<io::SetFundingSkew, Self::Env> {
            self.pending_call((coefficient_bps,))
        }
        fn set_liquidation_config(
            &mut self,
            penalty_bps: u16,
            fraction_bps: u16,
        ) -> sails_rs::client::PendingCall<io::SetLiquidationConfig, Self::Env> {
            self.pending_call((penalty_bps, fraction_bps))
        }
        fn set_oi_cap(
            &mut self,
            max_oi_per_side: u128,
        ) -> sails_rs::client::PendingCall<io::SetOiCap, Self::Env> {
            self.pending_call((max_oi_per_side,))
        }
        fn set_price_guard(
            &mut self,
            max_price_deviation_bps: u16,
        ) -> sails_rs::client::PendingCall<io::SetPriceGuard, Self::Env> {
            self.pending_call((max_price_deviation_bps,))
        }
        fn settle_funding(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::SettleFunding, Self::Env> {
            self.pending_call(())
        }
        fn update_price(
            &mut self,
            mark_price: u128,
            index_price: u128,
        ) -> sails_rs::client::PendingCall<io::UpdatePrice, Self::Env> {
            self.pending_call((mark_price, index_price))
        }
        fn config(&self) -> sails_rs::client::PendingCall<io::Config, Self::Env> {
            self.pending_call(())
        }
        fn fee_config(&self) -> sails_rs::client::PendingCall<io::FeeConfig, Self::Env> {
            self.pending_call(())
        }
        fn funding_skew(&self) -> sails_rs::client::PendingCall<io::FundingSkew, Self::Env> {
            self.pending_call(())
        }
        fn liquidation_fraction_bps(
            &self,
        ) -> sails_rs::client::PendingCall<io::LiquidationFractionBps, Self::Env> {
            self.pending_call(())
        }
        fn liquidation_penalty_bps(
            &self,
        ) -> sails_rs::client::PendingCall<io::LiquidationPenaltyBps, Self::Env> {
            self.pending_call(())
        }
        fn market_state(&self) -> sails_rs::client::PendingCall<io::MarketState, Self::Env> {
            self.pending_call(())
        }
        fn oi_cap(&self) -> sails_rs::client::PendingCall<io::OiCap, Self::Env> {
            self.pending_call(())
        }
        fn position(
            &self,
            position_id: u64,
        ) -> sails_rs::client::PendingCall<io::Position, Self::Env> {
            self.pending_call((position_id,))
        }
        fn positions(
            &self,
            trader: ActorId,
        ) -> sails_rs::client::PendingCall<io::Positions, Self::Env> {
            self.pending_call((trader,))
        }
        fn price_guard(&self) -> sails_rs::client::PendingCall<io::PriceGuard, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddMargin (position_id: u64, amount: u128) -> super::OpenPosition);
        sails_rs::io_struct_impl!(CheckLiquidation (trader: ActorId) -> bool);
        sails_rs::io_struct_impl!(ClosePosition (position_id: u64, size: u128) -> super::ClosedPosition);
        sails_rs::io_struct_impl!(OpenPosition (side: super::Side, size: u128, leverage: u16, margin: u128, max_slippage_bps: u16) -> super::OpenPosition);
        sails_rs::io_struct_impl!(SetFees (taker_fee_bps: u16) -> u16);
        sails_rs::io_struct_impl!(SetFundingSkew (coefficient_bps: u16) -> u16);
        sails_rs::io_struct_impl!(SetLiquidationConfig (penalty_bps: u16, fraction_bps: u16) -> ());
        sails_rs::io_struct_impl!(SetOiCap (max_oi_per_side: u128) -> u128);
        sails_rs::io_struct_impl!(SetPriceGuard (max_price_deviation_bps: u16) -> u16);
        sails_rs::io_struct_impl!(SettleFunding () -> super::MarketSnapshot);
        sails_rs::io_struct_impl!(UpdatePrice (mark_price: u128, index_price: u128) -> super::MarketSnapshot);
        sails_rs::io_struct_impl!(Config () -> super::MarketConfig);
        sails_rs::io_struct_impl!(FeeConfig () -> u16);
        sails_rs::io_struct_impl!(FundingSkew () -> u16);
        sails_rs::io_struct_impl!(LiquidationFractionBps () -> u16);
        sails_rs::io_struct_impl!(LiquidationPenaltyBps () -> u16);
        sails_rs::io_struct_impl!(MarketState () -> super::MarketSnapshot);
        sails_rs::io_struct_impl!(OiCap () -> u128);
        sails_rs::io_struct_impl!(Position (position_id: u64) -> super::PositionLookup);
        sails_rs::io_struct_impl!(Positions (trader: ActorId) -> Vec<super::OpenPosition>);
        sails_rs::io_struct_impl!(PriceGuard () -> u16);
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MarketConfig {
    pub owner: ActorId,
    pub asset: Asset,
    pub oracle_service: ActorId,
    pub margin_vault: ActorId,
    pub liquidity_pool: ActorId,
    pub session_registry: ActorId,
    pub risk: MarketRiskConfig,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Asset {
    Btc,
    Eth,
    Sol,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MarketRiskConfig {
    pub initial_margin_bps: u16,
    pub maintenance_margin_bps: u16,
    pub max_leverage: u16,
    pub funding_interval_blocks: u32,
    pub liquidation_delay_blocks: u32,
    pub max_funding_velocity_bps: i16,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct OpenPosition {
    pub id: u64,
    pub trader: ActorId,
    pub position: Position,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Position {
    pub size: i128,
    pub entry_price: u128,
    pub margin: u128,
    pub leverage: u16,
    pub last_funding_rate_bps: i128,
    pub opened_at: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ClosedPosition {
    pub realized_pnl: i128,
    pub funding_paid: i128,
    pub released_margin: u128,
    pub payout: u128,
    pub remaining_margin: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Side {
    Long,
    Short,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MarketSnapshot {
    pub mark_price: u128,
    pub index_price: u128,
    pub funding_rate_bps: i128,
    pub cumulative_funding_rate_bps: i128,
    pub open_interest_long: u128,
    pub open_interest_short: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PositionLookup {
    pub found: bool,
    pub position: OpenPosition,
}
