[package]
name = "liquidity-pool-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Generated Rust client for the Varix liquidity pool"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
ethexe = ["liquidity-pool-app/ethexe", "sails-rs/ethexe"]

[dependencies]
sails-rs.workspace = true

[build-dependencies]
liquidity-pool-app = { workspace = true, default-features = false }
sails-rs = { workspace = true, features = ["build"] }
