// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct OracleServiceClientProgram;
impl sails_rs::client::Program for OracleServiceClientProgram {}
pub trait OracleServiceClient {
    type Env: sails_rs::client::GearEnv;
    fn oracle(&self) -> sails_rs::client::Service<oracle::OracleImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> OracleServiceClient
    for sails_rs::client::Actor<OracleServiceClientProgram, E>
{
    type Env = E;
    fn oracle(&self) -> sails_rs::client::Service<oracle::OracleImpl, Self::Env> {
        self.service(stringify!(Oracle))
    }
}
pub trait OracleServiceClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        owner: ActorId,
    ) -> sails_rs::client::PendingCtor<OracleServiceClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> OracleServiceClientCtors
    for sails_rs::client::Deployment<OracleServiceClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        owner: ActorId,
    ) -> sails_rs::client::PendingCtor<OracleServiceClientProgram, io::Create, Self::Env> {
        self.pending_ctor((owner,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (owner: ActorId) -> ());
}

pub mod oracle {
    use super::*;
    pub trait Oracle {
        type Env: sails_rs::client::GearEnv;
        fn configure_relayer(
            &mut self,
            relayer: ActorId,
            verifying_key: Option<[u8; 32]>,
        ) -> sails_rs::client::PendingCall<io::ConfigureRelayer, Self::Env>;
        fn submit_price(
            &mut self,
            asset: Asset,
            price: u128,
            timestamp: u64,
            sig: Vec<u8>,
        ) -> sails_rs::client::PendingCall<io::SubmitPrice, Self::Env>;
        fn quote(&self, asset: Asset) -> sails_rs::client::PendingCall<io::Quote, Self::Env>;
    }
    pub struct OracleImpl;
    impl<E: sails_rs::client::GearEnv> Oracle for sails_rs::client::Service<OracleImpl, E> {
        type Env = E;
        fn configure_relayer(
            &mut self,
            relayer: ActorId,
            verifying_key: Option<[u8; 32]>,
        ) -> sails_rs::client::PendingCall<io::ConfigureRelayer, Self::Env> {
            self.pending_call((relayer, verifying_key))
        }
        fn submit_price(
            &mut self,
            asset: Asset,
            price: u128,
            timestamp: u64,
            sig: Vec<u8>,
        ) -> sails_rs::client::PendingCall<io::SubmitPrice, Self::Env> {
            self.pending_call((asset, price, timestamp, sig))
        }
        fn quote(&self, asset: Asset) -> sails_rs::client::PendingCall<io::Quote, Self::Env> {
            self.pending_call((asset,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(ConfigureRelayer (relayer: ActorId, verifying_key: Option<[u8; 32]>) -> ());
        sails_rs::io_struct_impl!(SubmitPrice (asset: super::Asset, price: u128, timestamp: u64, sig: Vec<u8>) -> super::OracleQuote);
        sails_rs::io_struct_impl!(Quote (asset: super::Asset) -> Option<super::OracleQuote>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum OracleEvents {
            RelayerConfigured {
                relayer: ActorId,
                enabled: bool,
            },
            PriceSubmitted {
                asset: Asset,
                price: u128,
                timestamp: u64,
                relayer: ActorId,
            },
        }
        impl sails_rs::client::Event for OracleEvents {
            const EVENT_NAMES: &'static [Route] = &["RelayerConfigured", "PriceSubmitted"];
        }
        impl sails_rs::client::ServiceWithEvents for OracleImpl {
            type Event = OracleEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Asset {
    Btc,
    Eth,
    Sol,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct OracleQuote {
    pub price: u128,
    pub timestamp: u64,
}
