constructor {
  Create : (owner: actor_id);
};

service Token {
  Approve : (spender: actor_id, value: u128) -> bool;
  Mint : (amount: u128) -> u128;
  MintTo : (to: actor_id, amount: u128) -> u128;
  Transfer : (to: actor_id, value: u128) -> bool;
  TransferFrom : (from: actor_id, to: actor_id, value: u128) -> bool;
  query Allowance : (owner: actor_id, spender: actor_id) -> u128;
  query BalanceOf : (owner: actor_id) -> u128;
  query Decimals : () -> u16;
  query TotalSupply : () -> u128;
};
