// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct MarginVaultClientProgram;
impl sails_rs::client::Program for MarginVaultClientProgram {}
pub trait MarginVaultClient {
    type Env: sails_rs::client::GearEnv;
    fn vault(&self) -> sails_rs::client::Service<vault::VaultImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> MarginVaultClient
    for sails_rs::client::Actor<MarginVaultClientProgram, E>
{
    type Env = E;
    fn vault(&self) -> sails_rs::client::Service<vault::VaultImpl, Self::Env> {
        self.service(stringify!(Vault))
    }
}
pub trait MarginVaultClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        owner: ActorId,
        session_registry: Option<ActorId>,
    ) -> sails_rs::client::PendingCtor<MarginVaultClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> MarginVaultClientCtors
    for sails_rs::client::Deployment<MarginVaultClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        owner: ActorId,
        session_registry: Option<ActorId>,
    ) -> sails_rs::client::PendingCtor<MarginVaultClientProgram, io::Create, Self::Env> {
        self.pending_ctor((owner, session_registry))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (owner: ActorId, session_registry: Option<ActorId>) -> ());
}

pub mod vault {
    use super::*;
    pub trait Vault {
        type Env: sails_rs::client::GearEnv;
        fn authorize_market(
            &mut self,
            market: ActorId,
        ) -> sails_rs::client::PendingCall<io::AuthorizeMarket, Self::Env>;
        fn deposit(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::Deposit, Self::Env>;
        fn lock_margin(
            &mut self,
            trader: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::LockMargin, Self::Env>;
        fn release_margin(
            &mut self,
            trader: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ReleaseMargin, Self::Env>;
        fn revoke_market(
            &mut self,
            market: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMarket, Self::Env>;
        fn slash_for_liquidation(
            &mut self,
            trader: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::SlashForLiquidation, Self::Env>;
        fn withdraw(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env>;
        fn account(&self, trader: ActorId)
        -> sails_rs::client::PendingCall<io::Account, Self::Env>;
        fn totals(&self) -> sails_rs::client::PendingCall<io::Totals, Self::Env>;
    }
    pub struct VaultImpl;
    impl<E: sails_rs::client::GearEnv> Vault for sails_rs::client::Service<VaultImpl, E> {
        type Env = E;
        fn authorize_market(
            &mut self,
            market: ActorId,
        ) -> sails_rs::client::PendingCall<io::AuthorizeMarket, Self::Env> {
            self.pending_call((market,))
        }
        fn deposit(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::Deposit, Self::Env> {
            self.pending_call((amount,))
        }
        fn lock_margin(
            &mut self,
            trader: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::LockMargin, Self::Env> {
            self.pending_call((trader, amount))
        }
        fn release_margin(
            &mut self,
            trader: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ReleaseMargin, Self::Env> {
            self.pending_call((trader, amount))
        }
        fn revoke_market(
            &mut self,
            market: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMarket, Self::Env> {
            self.pending_call((market,))
        }
        fn slash_for_liquidation(
            &mut self,
            trader: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::SlashForLiquidation, Self::Env> {
            self.pending_call((trader, amount))
        }
        fn withdraw(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env> {
            self.pending_call((amount,))
        }
        fn account(
            &self,
            trader: ActorId,
        ) -> sails_rs::client::PendingCall<io::Account, Self::Env> {
            self.pending_call((trader,))
        }
        fn totals(&self) -> sails_rs::client::PendingCall<io::Totals, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AuthorizeMarket (market: ActorId) -> ());
        sails_rs::io_struct_impl!(Deposit (amount: u128) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(LockMargin (trader: ActorId, amount: u128) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(ReleaseMargin (trader: ActorId, amount: u128) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(RevokeMarket (market: ActorId) -> ());
        sails_rs::io_struct_impl!(SlashForLiquidation (trader: ActorId, amount: u128) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(Withdraw (amount: u128) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(Account (trader: ActorId) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(Totals () -> super::VaultTotals);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum VaultEvents {
            Deposited {
                trader: ActorId,
                amount: u128,
                free_balance: u128,
            },
            Withdrawn {
                trader: ActorId,
                amount: u128,
                free_balance: u128,
            },
            MarginLocked {
                market: ActorId,
                trader: ActorId,
                amount: u128,
                account: AccountSnapshot,
            },
            MarginReleased {
                market: ActorId,
                trader: ActorId,
                amount: u128,
                account: AccountSnapshot,
            },
            MarginSlashed {
                market: ActorId,
                trader: ActorId,
                amount: u128,
                account: AccountSnapshot,
            },
            MarketAuthorizationChanged {
                market: ActorId,
                enabled: bool,
            },
        }
        impl sails_rs::client::Event for VaultEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "Deposited",
                "Withdrawn",
                "MarginLocked",
                "MarginReleased",
                "MarginSlashed",
                "MarketAuthorizationChanged",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for VaultImpl {
            type Event = VaultEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AccountSnapshot {
    pub free: u128,
    pub locked: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct VaultTotals {
    pub total_free: u128,
    pub total_locked: u128,
}
