// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct MarginVaultClientProgram;
impl sails_rs::client::Program for MarginVaultClientProgram {}
pub trait MarginVaultClient {
    type Env: sails_rs::client::GearEnv;
    fn vault(&self) -> sails_rs::client::Service<vault::VaultImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> MarginVaultClient
    for sails_rs::client::Actor<MarginVaultClientProgram, E>
{
    type Env = E;
    fn vault(&self) -> sails_rs::client::Service<vault::VaultImpl, Self::Env> {
        self.service(stringify!(Vault))
    }
}
pub trait MarginVaultClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        owner: ActorId,
        session_registry: ActorId,
        token_program: ActorId,
    ) -> sails_rs::client::PendingCtor<MarginVaultClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> MarginVaultClientCtors
    for sails_rs::client::Deployment<MarginVaultClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        owner: ActorId,
        session_registry: ActorId,
        token_program: ActorId,
    ) -> sails_rs::client::PendingCtor<MarginVaultClientProgram, io::Create, Self::Env> {
        self.pending_ctor((owner, session_registry, token_program))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (owner: ActorId, session_registry: ActorId, token_program: ActorId) -> ());
}

pub mod vault {
    use super::*;
    pub trait Vault {
        type Env: sails_rs::client::GearEnv;
        fn authorize_market(
            &mut self,
            market: ActorId,
        ) -> sails_rs::client::PendingCall<io::AuthorizeMarket, Self::Env>;
        /// Deduct a trading fee from a trader's free balance and forward the tokens
        /// to the liquidity pool. Called by an authorized market on trade execution.
        /// Strict: fails if the trader's free balance cannot cover the full fee.
        fn charge_fee(
            &mut self,
            trader: ActorId,
            amount: u128,
            pool: ActorId,
        ) -> sails_rs::client::PendingCall<io::ChargeFee, Self::Env>;
        fn deposit(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::Deposit, Self::Env>;
        fn lock_margin(
            &mut self,
            trader: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::LockMargin, Self::Env>;
        fn release_margin(
            &mut self,
            trader: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ReleaseMargin, Self::Env>;
        fn revoke_market(
            &mut self,
            market: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMarket, Self::Env>;
        fn settle_position(
            &mut self,
            trader: ActorId,
            released_margin: u128,
            payout: u128,
            pool: ActorId,
        ) -> sails_rs::client::PendingCall<io::SettlePosition, Self::Env>;
        fn slash_for_liquidation(
            &mut self,
            trader: ActorId,
            amount: u128,
            pool: ActorId,
        ) -> sails_rs::client::PendingCall<io::SlashForLiquidation, Self::Env>;
        fn withdraw(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env>;
        fn account(&self, trader: ActorId)
        -> sails_rs::client::PendingCall<io::Account, Self::Env>;
        fn totals(&self) -> sails_rs::client::PendingCall<io::Totals, Self::Env>;
    }
    pub struct VaultImpl;
    impl<E: sails_rs::client::GearEnv> Vault for sails_rs::client::Service<VaultImpl, E> {
        type Env = E;
        fn authorize_market(
            &mut self,
            market: ActorId,
        ) -> sails_rs::client::PendingCall<io::AuthorizeMarket, Self::Env> {
            self.pending_call((market,))
        }
        fn charge_fee(
            &mut self,
            trader: ActorId,
            amount: u128,
            pool: ActorId,
        ) -> sails_rs::client::PendingCall<io::ChargeFee, Self::Env> {
            self.pending_call((trader, amount, pool))
        }
        fn deposit(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::Deposit, Self::Env> {
            self.pending_call((amount,))
        }
        fn lock_margin(
            &mut self,
            trader: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::LockMargin, Self::Env> {
            self.pending_call((trader, amount))
        }
        fn release_margin(
            &mut self,
            trader: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ReleaseMargin, Self::Env> {
            self.pending_call((trader, amount))
        }
        fn revoke_market(
            &mut self,
            market: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMarket, Self::Env> {
            self.pending_call((market,))
        }
        fn settle_position(
            &mut self,
            trader: ActorId,
            released_margin: u128,
            payout: u128,
            pool: ActorId,
        ) -> sails_rs::client::PendingCall<io::SettlePosition, Self::Env> {
            self.pending_call((trader, released_margin, payout, pool))
        }
        fn slash_for_liquidation(
            &mut self,
            trader: ActorId,
            amount: u128,
            pool: ActorId,
        ) -> sails_rs::client::PendingCall<io::SlashForLiquidation, Self::Env> {
            self.pending_call((trader, amount, pool))
        }
        fn withdraw(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env> {
            self.pending_call((amount,))
        }
        fn account(
            &self,
            trader: ActorId,
        ) -> sails_rs::client::PendingCall<io::Account, Self::Env> {
            self.pending_call((trader,))
        }
        fn totals(&self) -> sails_rs::client::PendingCall<io::Totals, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AuthorizeMarket (market: ActorId) -> ());
        sails_rs::io_struct_impl!(ChargeFee (trader: ActorId, amount: u128, pool: ActorId) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(Deposit (amount: u128) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(LockMargin (trader: ActorId, amount: u128) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(ReleaseMargin (trader: ActorId, amount: u128) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(RevokeMarket (market: ActorId) -> ());
        sails_rs::io_struct_impl!(SettlePosition (trader: ActorId, released_margin: u128, payout: u128, pool: ActorId) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(SlashForLiquidation (trader: ActorId, amount: u128, pool: ActorId) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(Withdraw (amount: u128) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(Account (trader: ActorId) -> super::AccountSnapshot);
        sails_rs::io_struct_impl!(Totals () -> super::VaultTotals);
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AccountSnapshot {
    pub free: u128,
    pub locked: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct VaultTotals {
    pub total_free: u128,
    pub total_locked: u128,
}
