[package]
name = "funding-scheduler-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Generated Rust client for Varix funding scheduler"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
sails-rs.workspace = true

[build-dependencies]
funding-scheduler-app.workspace = true
sails-rs = { workspace = true, features = ["build"] }
