[package]
name = "margin-vault-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Generated Rust client for Varix margin vault"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
ethexe = ["margin-vault-app/ethexe", "sails-rs/ethexe"]

[dependencies]
sails-rs.workspace = true

[build-dependencies]
margin-vault-app = { workspace = true, default-features = false }
sails-rs = { workspace = true, features = ["build"] }
