// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct DemoUsdcVftClientProgram;
impl sails_rs::client::Program for DemoUsdcVftClientProgram {}
pub trait DemoUsdcVftClient {
    type Env: sails_rs::client::GearEnv;
    fn token(&self) -> sails_rs::client::Service<token::TokenImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> DemoUsdcVftClient
    for sails_rs::client::Actor<DemoUsdcVftClientProgram, E>
{
    type Env = E;
    fn token(&self) -> sails_rs::client::Service<token::TokenImpl, Self::Env> {
        self.service(stringify!(Token))
    }
}
pub trait DemoUsdcVftClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        owner: ActorId,
    ) -> sails_rs::client::PendingCtor<DemoUsdcVftClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> DemoUsdcVftClientCtors
    for sails_rs::client::Deployment<DemoUsdcVftClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        owner: ActorId,
    ) -> sails_rs::client::PendingCtor<DemoUsdcVftClientProgram, io::Create, Self::Env> {
        self.pending_ctor((owner,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (owner: ActorId) -> ());
}

pub mod token {
    use super::*;
    pub trait Token {
        type Env: sails_rs::client::GearEnv;
        fn approve(
            &mut self,
            spender: ActorId,
            value: u128,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env>;
        fn mint(&mut self, amount: u128) -> sails_rs::client::PendingCall<io::Mint, Self::Env>;
        fn mint_to(
            &mut self,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::MintTo, Self::Env>;
        fn transfer(
            &mut self,
            to: ActorId,
            value: u128,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env>;
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: u128,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env>;
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env>;
        fn balance_of(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env>;
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env>;
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env>;
    }
    pub struct TokenImpl;
    impl<E: sails_rs::client::GearEnv> Token for sails_rs::client::Service<TokenImpl, E> {
        type Env = E;
        fn approve(
            &mut self,
            spender: ActorId,
            value: u128,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env> {
            self.pending_call((spender, value))
        }
        fn mint(&mut self, amount: u128) -> sails_rs::client::PendingCall<io::Mint, Self::Env> {
            self.pending_call((amount,))
        }
        fn mint_to(
            &mut self,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::MintTo, Self::Env> {
            self.pending_call((to, amount))
        }
        fn transfer(
            &mut self,
            to: ActorId,
            value: u128,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env> {
            self.pending_call((to, value))
        }
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: u128,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env> {
            self.pending_call((from, to, value))
        }
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env> {
            self.pending_call((owner, spender))
        }
        fn balance_of(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env> {
            self.pending_call((owner,))
        }
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env> {
            self.pending_call(())
        }
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Approve (spender: ActorId, value: u128) -> bool);
        sails_rs::io_struct_impl!(Mint (amount: u128) -> u128);
        sails_rs::io_struct_impl!(MintTo (to: ActorId, amount: u128) -> u128);
        sails_rs::io_struct_impl!(Transfer (to: ActorId, value: u128) -> bool);
        sails_rs::io_struct_impl!(TransferFrom (from: ActorId, to: ActorId, value: u128) -> bool);
        sails_rs::io_struct_impl!(Allowance (owner: ActorId, spender: ActorId) -> u128);
        sails_rs::io_struct_impl!(BalanceOf (owner: ActorId) -> u128);
        sails_rs::io_struct_impl!(Decimals () -> u16);
        sails_rs::io_struct_impl!(TotalSupply () -> u128);
    }
}
