[package]
name = "oracle-service-app"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Business logic for Varix signed price submissions"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ed25519-dalek.workspace = true
sails-rs.workspace = true
varix-shared.workspace = true
