[package]
name = "demo-usdc-vft-app"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Business logic for demo USDC VFT"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
ethexe = ["sails-rs/ethexe"]

[dependencies]
sails-rs.workspace = true
