[package]
name = "market-factory-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Generated Rust client for Varix market factory"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
sails-rs.workspace = true

[build-dependencies]
market-factory-app.workspace = true
sails-rs = { workspace = true, features = ["build"] }
