// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct SessionRegistryClientProgram;
impl sails_rs::client::Program for SessionRegistryClientProgram {}
pub trait SessionRegistryClient {
    type Env: sails_rs::client::GearEnv;
    fn session_registry(
        &self,
    ) -> sails_rs::client::Service<session_registry::SessionRegistryImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> SessionRegistryClient
    for sails_rs::client::Actor<SessionRegistryClientProgram, E>
{
    type Env = E;
    fn session_registry(
        &self,
    ) -> sails_rs::client::Service<session_registry::SessionRegistryImpl, Self::Env> {
        self.service(stringify!(SessionRegistry))
    }
}
pub trait SessionRegistryClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self)
    -> sails_rs::client::PendingCtor<SessionRegistryClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> SessionRegistryClientCtors
    for sails_rs::client::Deployment<SessionRegistryClientProgram, E>
{
    type Env = E;
    fn new(
        self,
    ) -> sails_rs::client::PendingCtor<SessionRegistryClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> ());
}

pub mod session_registry {
    use super::*;
    pub trait SessionRegistry {
        type Env: sails_rs::client::GearEnv;
        fn register_session(
            &mut self,
            session_key: ActorId,
            expires_at: u32,
            permissions: SessionPermissions,
        ) -> sails_rs::client::PendingCall<io::RegisterSession, Self::Env>;
        fn revoke_session(
            &mut self,
            session_key: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeSession, Self::Env>;
        fn active_session(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::ActiveSession, Self::Env>;
        fn owner_for(
            &self,
            session_key: ActorId,
        ) -> sails_rs::client::PendingCall<io::OwnerFor, Self::Env>;
        fn validate(
            &self,
            owner: ActorId,
            session_key: ActorId,
            action: SessionAction,
        ) -> sails_rs::client::PendingCall<io::Validate, Self::Env>;
    }
    pub struct SessionRegistryImpl;
    impl<E: sails_rs::client::GearEnv> SessionRegistry
        for sails_rs::client::Service<SessionRegistryImpl, E>
    {
        type Env = E;
        fn register_session(
            &mut self,
            session_key: ActorId,
            expires_at: u32,
            permissions: SessionPermissions,
        ) -> sails_rs::client::PendingCall<io::RegisterSession, Self::Env> {
            self.pending_call((session_key, expires_at, permissions))
        }
        fn revoke_session(
            &mut self,
            session_key: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeSession, Self::Env> {
            self.pending_call((session_key,))
        }
        fn active_session(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::ActiveSession, Self::Env> {
            self.pending_call((owner,))
        }
        fn owner_for(
            &self,
            session_key: ActorId,
        ) -> sails_rs::client::PendingCall<io::OwnerFor, Self::Env> {
            self.pending_call((session_key,))
        }
        fn validate(
            &self,
            owner: ActorId,
            session_key: ActorId,
            action: SessionAction,
        ) -> sails_rs::client::PendingCall<io::Validate, Self::Env> {
            self.pending_call((owner, session_key, action))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(RegisterSession (session_key: ActorId, expires_at: u32, permissions: super::SessionPermissions) -> super::SessionRecord);
        sails_rs::io_struct_impl!(RevokeSession (session_key: ActorId) -> bool);
        sails_rs::io_struct_impl!(ActiveSession (owner: ActorId) -> Option<super::SessionRecord>);
        sails_rs::io_struct_impl!(OwnerFor (session_key: ActorId) -> Option<ActorId>);
        sails_rs::io_struct_impl!(Validate (owner: ActorId, session_key: ActorId, action: super::SessionAction) -> bool);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum SessionRegistryEvents {
            SessionRegistered {
                owner: ActorId,
                session_key: ActorId,
                expires_at: u32,
            },
            SessionRevoked {
                owner: ActorId,
                session_key: ActorId,
            },
        }
        impl sails_rs::client::Event for SessionRegistryEvents {
            const EVENT_NAMES: &'static [Route] = &["SessionRegistered", "SessionRevoked"];
        }
        impl sails_rs::client::ServiceWithEvents for SessionRegistryImpl {
            type Event = SessionRegistryEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SessionPermissions {
    pub trade: bool,
    pub add_margin: bool,
    pub withdraw: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SessionRecord {
    pub owner: ActorId,
    pub session_key: ActorId,
    pub expires_at: u32,
    pub permissions: SessionPermissions,
    pub registered_at: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum SessionAction {
    Trade,
    AddMargin,
    Withdraw,
}
