[package]
name = "perp-market-app"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Business logic for Varix isolated perpetual market"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
sails-rs.workspace = true
session-registry-client.workspace = true
varix-shared.workspace = true
